### PR TITLE
Only run code standards checks on changed files

### PR DESCRIPTION
**Pull request by andybroomfield**
Use the action https://github.com/marketplace/actions/action-phpcs so that only changed files are checked against coding standards.

## Accessibility

-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

### CODE REVIEW

**Comment by andybroomfield** [comment]
@millnut how would I test this?

**Comment by millnut** [comment]
Hi @andybroomfield similar to this PR https://github.com/localgovdrupal/localgov_alert_banner/pull/371/files

**Comment by andybroomfield** [comment]
thanks @millnut I'll take a look. This is just an expriment to test the idea for now.

**Comment by andybroomfield** [comment]
Well this doesn't appear to work https://github.com/localgovdrupal/localgov_alert_banner/actions/runs/11221747683/job/31192805610?pr=384

**Pull request closed without merging**
