### PR TITLE
ci: add ESLint and Stylelint checks to workflows

### PR DESCRIPTION
**Pull request by millnut**
## What does this change?

Adds #10 and #12 in this PR which adds the following checks to the workflows, using Drupal Core's recommended coding standards

- ESLint for js files if they exist
- ESLint for yml files if they exist
- Stylelint for css files if they exist

This will be useful to have in place as these checks are also part of the drupal.org contrib pipelines which use GitLab should modules move to there in future.

The ESLint and Stylelint checks are on by default, but do not prevent phpunit from running.

~Currently to show it working `continue-on-error` is commented out, we will need to discuss whether to use `continue-on-error: true`. The downside to this is that GitHub UI will show a green tick and it's down to the user to check if it has succeeded manually. There is a long discussion at https://github.com/orgs/community/discussions/15452 asking GitHub to introduce a warning/skipped/orange colour similar to GitLab.~

## How to test

Example on alert banner: https://github.com/localgovdrupal/localgov_alert_banner/actions/runs/12215511355

Example on base theme: https://github.com/localgovdrupal/localgov_base/actions/runs/12215438152

Example job vacancies (no php files): https://github.com/localgovdrupal/localgov_job_vacancies/actions/runs/12215522991

### CODE REVIEW

**Comment by ekes** [comment]
> Currently to show it working continue-on-error is commented out, we will need to discuss whether to use continue-on-error: true.

I assume we're going to have a plan for tidying up the errors these tests are highlighting? As I see the two examples are failing. In the meantime however not preventing releases that aren't increasing errors would be good I think.

**Comment by millnut** [comment]
> > Currently to show it working continue-on-error is commented out, we will need to discuss whether to use continue-on-error: true.
> 
> I assume we're going to have a plan for tidying up the errors these tests are highlighting? As I see the two examples are failing. In the meantime however not preventing releases that aren't increasing errors would be good I think.

Correct I'm looking into seeing if there is a way to surface the errors in the summary and allowing it to fail and continue.

I'll mark this as draft until I've looked into this some more.

**Comment by ekes** [comment]
MT: Question is there a baseline file we could add?

**Comment by markconroy** [comment]
I love this idea. And I don't think it should take us too long to have all our files formatted correctly.

In fact, I could take it as my next week's project so we could start using this very soon.

**Comment by millnut** [comment]
Hi @markconroy @ekes I've updated the workflow to ignore the PHPStan check if there are no php files present, I've added job_vacancies as an example to show this is skipped now and ran the existing examples again.

I've looked into ESLint and Stylelint and neither have baseline functionality available, there have been feature requests but all were marked as closed. 

I've double-checked how this works on the drupal org CI and the only difference is they can show a warning state due to it being GitLab and GitHub only has success or failure.

Maybe it's one we discuss next MT, most if not all of the errors reported can be fixed automatically in my limited testing. Some we may need to ignore based on how our styling needs to work versus Drupal Core.

**Comment by millnut** [comment]
Hoping to pick this up again later this week, to resolve conflicts and remove the requirement for passing eslint/stylelint before phpunit will start.

**Pull request merged**
